ARMA3_DG_ClassID = {
    "MIL_TRUCK"   :0,  
    "MIL_VEHICLE" :1,     
    "MIL_APC"     :2, 
    "MIL_IFV"     :3, 
    "MIL_MBT"     :4, 
    "MIL_MED"     :5, 
    "MIL_BOAT"    :6,  
    "MIL_SHIP"    :7,  
    "POLICE"      :8, 
    "CIV_VEHICLE" :9,     
    "CIV_BOAT"    :10,  
    "CIV_SHIP"    :11,  
    "CIV_MEDICAL" :12     
}
ARMA3_DG_ClassNames = {
    0 :"MIL_TRUCK"   ,  
    1 :"MIL_VEHICLE" ,     
    2 :"MIL_APC"     , 
    3 :"MIL_IFV"     , 
    4 :"MIL_MBT"     , 
    5 :"MIL_MED"     , 
    6 :"MIL_BOAT"    ,  
    7 :"MIL_SHIP"    ,  
    8 :"POLICE"      , 
    9 :"CIV_VEHICLE" ,     
    10:"CIV_BOAT"    ,  
    11:"CIV_SHIP"    ,  
    12:"CIV_MEDICAL"      
}
ARMA3_DG_vehiclesClasses = {
    "B_Truck_01_ammo_F"                             : "MIL_TRUCK",
    "Unimog1550_Ammo2"                              : "MIL_TRUCK",
    "Unimog1550_SemiCovered2"                       : "MIL_TRUCK",
    "Unimog1550_Fuel2"                              : "MIL_TRUCK",
    "Unimog1550_Covered2"                           : "MIL_TRUCK",
    "TMT_Unimog_Tranport"                           : "MIL_TRUCK",
    "TMT_Unimog_Tranport_W"                         : "MIL_TRUCK",
    "rhsusf_M1078A1P2_D_fmtv_usarmy"                : "MIL_TRUCK",
    "rhsusf_M1078A1P2_D_flatbed_fmtv_usarmy"        : "MIL_TRUCK",
    "rhsusf_M1078A1P2_B_D_fmtv_usarmy"              : "MIL_TRUCK",
    "rhsusf_M1078A1P2_B_D_flatbed_fmtv_usarmy"      : "MIL_TRUCK",
    "rhsusf_M1078A1P2_B_M2_D_fmtv_usarmy"           : "MIL_TRUCK",
    "rhsusf_M1078A1P2_B_M2_D_flatbed_fmtv_usarmy"   : "MIL_TRUCK",
    "rhsusf_M1083A1P2_D_flatbed_fmtv_usarmy"        : "MIL_TRUCK",
    "rhsusf_M1083A1P2_B_M2_D_fmtv_usarmy"           : "MIL_TRUCK",
    "rhsusf_M1084A1P2_D_fmtv_usarmy"                : "MIL_TRUCK",
    "rhsusf_M1084A1P2_B_D_fmtv_usarmy"              : "MIL_TRUCK",
    "UK3CB_B_M939_Closed_DES"                       : "MIL_TRUCK",
    "UK3CB_B_M939_Guntruck_DES"                     : "MIL_TRUCK",
    "UK3CB_B_M939_Open_DES"                         : "MIL_TRUCK",
    "UK3CB_B_M939_Refuel_DES"                       : "MIL_TRUCK",
    "UK3CB_B_M939_Recovery_DES"                     : "MIL_TRUCK",
    "rhsusf_M977A4_AMMO_usarmy_d"                   : "MIL_TRUCK",
    "rhsusf_M977A4_AMMO_BKIT_usarmy_d"              : "MIL_TRUCK",
    "rhsusf_M977A4_REPAIR_BKIT_M2_usarmy_d"         : "MIL_TRUCK",
    "rhsusf_M978A4_BKIT_usarmy_d"                   : "MIL_TRUCK",
    "UK3CB_B_MTVR_Closed_DES"                       : "MIL_TRUCK",
    "UK3CB_B_MTVR_Reammo_DES"                       : "MIL_TRUCK",
    "rhsusf_M978A4_usarmy_d"                        : "MIL_TRUCK",
    "UK3CB_B_MTVR_Open_DES"                         : "MIL_TRUCK",
    "UK3CB_B_MTVR_Recovery_DES"                     : "MIL_TRUCK",

    "HAFM_GD240_Patrol2"                : "MIL_VEHICLE",
    "HAFM_GD240_Unarmed2"               : "MIL_VEHICLE",
    "HAFM_HMMWV1_Kornet"                : "MIL_VEHICLE",
    "HAFM_HMMWV1_TOW"                   : "MIL_VEHICLE",
    "HAFM_VBL2_M50"                     : "MIL_VEHICLE",
    "HAFM_VBL2"                         : "MIL_VEHICLE",
    "TMT_Cobra_RCWS_E"                  : "MIL_VEHICLE",
    "TMT_Cobra_RCWS_W"                  : "MIL_VEHICLE",
    "TMT_Kirpill_MRAP_E"                : "MIL_VEHICLE",
    "TMT_Kirpill_MRAP_W"                : "MIL_VEHICLE",
    "TMT_Ejder_RCWS_GEN"                : "MIL_VEHICLE",    
    "tmt_landrover"                     : "MIL_VEHICLE",
    "tmt_landrover_w"                   : "MIL_VEHICLE",
    "rhsusf_m1025_w_s_m2"               : "MIL_VEHICLE",
    "rhsusf_m1025_w_s_Mk19"             : "MIL_VEHICLE",
    "rhsusf_m1025_w_s"                  : "MIL_VEHICLE",
    "rhsusf_m1043_w_s_m2"               : "MIL_VEHICLE",
    "rhsusf_m1043_w_s_mk19"             : "MIL_VEHICLE",
    "rhsusf_m1043_w_s"                  : "MIL_VEHICLE",
    "rhsusf_m1045_w_s"                  : "MIL_VEHICLE",
    "rhsusf_m998_w_s_4dr_halftop"       : "MIL_VEHICLE",
    "rhsusf_m998_w_s_2dr_fulltop"       : "MIL_VEHICLE",

    "Leonidas2_2"                       :"MIL_APC",
    "Leonidas3_BLU"                     :"MIL_APC",
    "blx_m1117_GR"                      :"MIL_APC",
    "TMT_ACV300_E_M2"                   :"MIL_APC",
    "TMT_ACV300_W_M2"                   :"MIL_APC",
    "TMT_ACV300_E_M242"                 :"MIL_APC",
    "TMT_ACV300_W_M242"                 :"MIL_APC",
    "TMT_M113_E_M2"                     :"MIL_APC",
    "TMT_M113_W_M2"                     :"MIL_APC",
    "TMT_Arma_GMG_HMG"                  :"MIL_APC",
    "rhsusf_M1117_D"                    :"MIL_APC",
    "rhsusf_M1117_0"                    :"MIL_APC",
    "rhsusf_M1220_usarmy_d"             :"MIL_APC",
    "rhsusf_M1220_M153_M2_usarmy_d"     :"MIL_APC",
    "rhsusf_M1220_M153_MK19_usarmy_d"   :"MIL_APC",
    "rhsusf_M1220_M2_usarmy_d"          :"MIL_APC",
    "rhsusf_M1220_MK19_usarmy_d"        :"MIL_APC",
    "rhsusf_M1230_M2_usarmy_d"          :"MIL_APC",
    "rthsusf_M1230_MK19_usarmy_d"       :"MIL_APC",
    "rhsusf_M1230a1_usarmy_d"           :"MIL_APC",
    "rhsusf_M1232_usarmy_d"             :"MIL_APC",
    "rhsusf_M1232_M2_usarmy_d"          :"MIL_APC",
    "rhsusf_M1232_MK19_usarmy_d"        :"MIL_APC",
    "rhsusf_M1237_M2_usarmy_d"          :"MIL_APC",
    "rhsusf_M1237_MK19_usarmy_d"        :"MIL_APC",
    "rhsusf_m1240a1_usarmy_d"           :"MIL_APC",
    "rhsusf_m1240a1_m2_usarmy_d"        :"MIL_APC",
    "rhsusf_m1240a1_m240_usarmy_d"      :"MIL_APC",
    "rhsusf_m1240a1_mk19_usarmy_d"      :"MIL_APC",
    "rhsusf_m1240a1_m2crows_usarmy_d"   :"MIL_APC",
    "UK3CB_B_MaxxPro_MK19_US"           :"MIL_APC",
    "UK3CB_B_MaxxPro_M2_US"             :"MIL_APC",
    "rhsusf_m1240a1_mk19crows_usarmy_d" :"MIL_APC",
    "rhsusf_m1240a1_mk19_uik_usarmy_d"  :"MIL_APC",

    "RHS_M2A2"                          :"MIL_IFV",
    "RHS_M2A2_BUSKI"                    :"MIL_IFV",
    "RHS_M2A3"                          :"MIL_IFV",
    "RHS_M2A3_BUSKI"                    :"MIL_IFV",
    "RHS_M2A3_BUSKIII"                  :"MIL_IFV",
    "RHS_M6"                            :"MIL_IFV",

    "GR_MBT_MLRS"                       : "MIL_MBT",
    "Leopard2A6HEL_2"                   : "MIL_MBT",
    "Leopard1A4_2"                      : "MIL_MBT",
    "Leopard2A4_2"                      : "MIL_MBT",
    "M60A3_2"                           : "MIL_MBT",
    "TMT_T155_E"                        : "MIL_MBT",
    "TMT_T155_W"                        : "MIL_MBT",
    "TMT_Leopard2_NG_D"                 : "MIL_MBT",
    "TMT_Leopard2_NG_W"                 : "MIL_MBT",
    "TMT_LEO2A4_w"                      : "MIL_MBT",
    "TMT_LEO2A4_E"                      : "MIL_MBT",
    "TMT_M60A3_E"                       : "MIL_MBT",
    "TMT_M60A3_W"                       : "MIL_MBT",
    "rhsusf_m109d_usarmy"               : "MIL_MBT",
    "rhsusf_M142_usarmy_D"              : "MIL_MBT",
    "UK3CB_B_M270_MLRS_Cluster_DES"     : "MIL_MBT",
    "UK3CB_B_M270_MLRS_HE_DES"          : "MIL_MBT",


    "TMT_M113_E_Amb"                    :"MIL_MED",
    "TMT_M113_W_Amb"                    :"MIL_MED",
    "TMT_ACV300_E_Amb"                  :"MIL_MED",
    "TMT_ACV300_W_Amb"                  :"MIL_MED",
    "TMT_Kirpill_AMB_E"                 :"MIL_MED",
    "TMT_Kirpill_AMB_W"                 :"MIL_MED",
    "tmt_landrover_amb"                 :"MIL_MED",
    "tmt_landrover_amb_w"               :"MIL_MED",

    "HAFM_Naval_CB90_BLU"           : "MIL_BOAT",
    "HAFM_Naval_RHIB"               : "MIL_BOAT",
    "HAFM_Naval_GunBoat_BLU"        : "MIL_BOAT",
    "rhsgref_hidf_assault_boat"     : "MIL_BOAT",
    "rhsgref_hidf_rhib"             : "MIL_BOAT",
    "B_Boat_Transport_01_F"         : "MIL_BOAT",
    "B_Lifeboat"                    : "MIL_BOAT",
    "B_Boat_Armed_01_minigun_F"     : "MIL_BOAT",
    "HAFM_CB90_BLU"                 : "MIL_BOAT",
    "HAFM_GunBoat_BLU"              : "MIL_BOAT",
    "HAFM_Russen"                   : "MIL_BOAT",
    "rhsusf_mkvsoc"                 : "MIL_BOAT",
    "SBOMB_CAR7"                    : "MIL_BOAT",

    "Land_Carrier_01_base_F"        : "MIL_SHIP",
    "Land_Destroyer_01_base_F"      : "MIL_SHIP",
    "sab_nl_akagi"                  : "MIL_SHIP",
    "sab_nl_drone_a6m"              : "MIL_SHIP",
    "sab_nl_mutsuki"                : "MIL_SHIP",
    "sab_nl_scharnhorst"            : "MIL_SHIP",
    "sab_nl_t22"                    : "MIL_SHIP",
    "sab_nl_vincenzo"               : "MIL_SHIP",
    "sab_nl_zara"                   : "MIL_SHIP",
    "HAFM_Naval_Russen"             : "MIL_SHIP",
    "HAFM_ABurke"                   : "MIL_SHIP",
    "HAFM_MEKO_TN"                  : "MIL_SHIP",
    "HAFM_FREMM"                    : "MIL_SHIP",
    "HAFM_MEKO_HN"                  : "MIL_SHIP",
    "HAFM_Replenishment"            : "MIL_SHIP",


    "UK3CB_APD_B_Transit_Cargo"         : "POLICE",
    "UK3CB_APD_B_LandRover_M2"          : "POLICE",
    "UK3CB_APD_B_MB4WD_Unarmed"         : "POLICE",
    "UK3CB_CPD_B_UAZ_Closed"            : "POLICE",
    "UK3CB_APD_B_Transit_Transport"     : "POLICE",
    "UK3CB_APD_B_Offroad_Comms_EKAM"    : "POLICE",
    "UK3CB_APD_B_Offroad_Unarmed"       : "POLICE",
    "UK3CB_APD_B_Offroad_HMG_EKAM"      : "POLICE",
    "UK3CB_APD_B_Hilux_M2"              : "POLICE",
    "UK3CB_APD_B_SUV_POL"               : "POLICE",
    "UK3CB_APD_B_Offroad_Services_EKAM" : "POLICE",
    "UK3CB_APD_B_LandRover_Closed"      : "POLICE",
    "Offroad Covered"                   : "POLICE",
    "UK3CB_APD_B_Offroad_Covered_EKAM"  : "POLICE",
    "walker_A3_PoliceSUV"               : "POLICE",
    "UK3CB_CPD_B_TIGR"                  : "POLICE",
    "UK3CB_CPD_B_Hilux_Pkm"             : "POLICE",
    "UK3CB_APD_B_Hilux_Closed"          : "POLICE",
    "UK3CB_CPD_B_TIGR_FFV"              : "POLICE",
    "UK3CB_APD_B_Landcruiser_POL"       : "POLICE",
    "UK3CB_APD_B_Pickup_M2"             : "POLICE",
    "UK3CB_APD_B_Hilux_Open"            : "POLICE",
    "UK3CB_APD_B_Transit_Medevac"       : "POLICE",
    "UK3CB_APD_B_YAVA"                  : "POLICE",
    "UK3CB_APD_B_Quadbike"              : "POLICE",
 
    "UK3CB_ADC_C_V3S_Closed"            : "CIV_VEHICLE",
    "walker_a3_sedan"                   : "CIV_VEHICLE",
    "walker_a3_c_datsun"                : "CIV_VEHICLE",
    "walker_a3_datsun_2"                : "CIV_VEHICLE",
    "walker_a3_octavia_orange"          : "CIV_VEHICLE",
    "UK3CB_ADC_C_Kamaz_Fuel"            : "CIV_VEHICLE",
    "UK3CB_ADC_C_Hilux_Civ_Closed"      : "CIV_VEHICLE",
    "UK3CB_ADC_C_Hatchback"             : "CIV_VEHICLE",
    "UK3CB_ADC_C_Tractor"               : "CIV_VEHICLE",
    "walker_a3_datsun"                  : "CIV_VEHICLE",
    "UK3CB_ADC_C_Kamaz_Open"            : "CIV_VEHICLE",
    "walker_a3_buscity_blue"            : "CIV_VEHICLE",
    "walker_a3_octavia_black"           : "CIV_VEHICLE",
    "walker_a3_octavia_red"             : "CIV_VEHICLE",
    "UK3CB_ADC_C_Sedan"                 : "CIV_VEHICLE",
    "C_Truck_02_fuel_F"                 : "CIV_VEHICLE",
    "UK3CB_ADC_C_Tractor_Old"           : "CIV_VEHICLE",
    "walker_a3_skodovka"                : "CIV_VEHICLE",
    "C_Hatchback_01_F"                  : "CIV_VEHICLE",
    "walker_a3_skodovka_2"              : "CIV_VEHICLE",
    "walker_a3_s1203"                   : "CIV_VEHICLE",
    "walker_a3_octavia_blue"            : "CIV_VEHICLE",
    "UK3CB_C_Datsun_Closed"             : "CIV_VEHICLE",
    "UK3CB_ADC_C_LR_Closed"             : "CIV_VEHICLE",
    "UK3CB_ADC_C_Ikarus"                : "CIV_VEHICLE",
    "UK3CB_ADC_C_Golf"                  : "CIV_VEHICLE",
    "UK3CB_ADC_C_YAVA"                  : "CIV_VEHICLE",
    "UK3CB_ADC_C_Pickup"                : "CIV_VEHICLE",
    "walker_a3_octavia_white"           : "CIV_VEHICLE",
    "UK3CB_ADC_C_Hilux_Civ_Open"        : "CIV_VEHICLE",
    "UK3CB_ADC_C_TT650"                 : "CIV_VEHICLE",
    "UK3CB_ADC_C_V3S_Refuel"            : "CIV_VEHICLE",
    "UK3CB_ADC_C_Octavia"               : "CIV_VEHICLE",
    "UK3CB_ADC_C_Kamaz_Covered"         : "CIV_VEHICLE",
    "UK3CB_ADC_C_V3S_Open"              : "CIV_VEHICLE",
    "walker_a3_SUV"                     : "CIV_VEHICLE",
    "UK3CB_ADC_C_Landcruiser"           : "CIV_VEHICLE",
    "walker_A3_CivSUV"                  : "CIV_VEHICLE",
    "UK3CB_ADC_C_S1203"                 : "CIV_VEHICLE",
    "walker_a3_tractor"                 : "CIV_VEHICLE",
    "walker_a3_tractor_1"               : "CIV_VEHICLE",
    "walker_a3_uaz_civil"               : "CIV_VEHICLE",
    "walker_a3_buscity"                 : "CIV_VEHICLE",
    "UK3CB_ADC_C_Forklift"              : "CIV_VEHICLE",

    "walker_A3_boat_f"                  : "CIV_BOAT",
    "walker_A3_smallb_f"                : "CIV_BOAT",
    "walker_A3_smallb_e"                : "CIV_BOAT",
    "UK3CB_ADC_C_Fishing_Boat"          : "CIV_BOAT",
    "UK3CB_ADC_C_Fishing_Vessel"        : "CIV_BOAT",
    "UK3CB_ADC_C_Small_Boat_wood"       : "CIV_BOAT",
    "sab_nl_vessel_a"                   : "CIV_BOAT",
    "sab_nl_vessel_b"                   : "CIV_BOAT",
    "sab_nl_vessel_c"                   : "CIV_BOAT",
    "sab_nl_vessel_d"                   : "CIV_BOAT",

    "Lexx_ContainerShip_Black_Empty_H"     : "CIV_SHIP",
    "Lexx_ContainerShip_Blue_Loaded_H"     : "CIV_SHIP",
    "Lexx_ContainerShip_Green_Loaded_H"    : "CIV_SHIP",
    "Lexx_CruiseShip_Blue_H"               : "CIV_SHIP",

    "UK3CB_MEC_B_Van_Transit_Medevac"      : "CIV_MEDICAL",
    "UK3CB_MEC_B_S1203_Amb"                : "CIV_MEDICAL",
    "UK3CB_MEC_B_Hilux_Ambulance"          : "CIV_MEDICAL",
    "UK3CB_MEC_C_Hilux_Ambulance"          : "CIV_MEDICAL",
    "UK3CB_C_S1203_Ambulance"              : "CIV_MEDICAL",
    "UK3CB_LSM_B_MTLB_AMB"                 : "CIV_MEDICAL",
    "UK3CB_ION_B_Winter_Hilux_Ambulance"   : "CIV_MEDICAL",
    "UK3CB_ION_B_Woodland_Hilux_Ambulance" : "CIV_MEDICAL",
    "UK3CB_ION_B_Woodland_Transit_Medevac" : "CIV_MEDICAL",
    "UK3CB_ION_B_Winter_Transit_Medevac"   : "CIV_MEDICAL",
    "C_IDAP_Van_02_medevac_F"              : "CIV_MEDICAL",
    "UK3CB_C_S1203_Ambulance_MEC"          : "CIV_MEDICAL",
    "UK3CB_C_Hilux_Ambulance"              : "CIV_MEDICAL",
    "UK3CB_APD_B_Hilux_Ambulance"          : "CIV_MEDICAL",
    "UK3CB_KRG_B_MTLB_AMB"                 : "CIV_MEDICAL",
    "AF_C_Ambulance_cute_F"                : "CIV_MEDICAL",
    "UK3CB_MEC_C_Van_Transit_Medevac"      : "CIV_MEDICAL",
    "walker_a3_s1203amb"                   : "CIV_MEDICAL",
    "C_VAN_02_medevac_F"                   : "CIV_MEDICAL",
}                   