	// Names of the Vehicles must match the Official names of the game
	vehicle_names = ["GR_MBT_MLRS",                   
					"Leopard2A6HEL_2"               ,
					"Leopard1A4_2"                  ,
					"Leopard2A4_2"                  ,
					"M60A3_2"                       ,
					"TMT_T115_E"                    ,
					"TMT_T115_W"                    ,
					"TMT_Leopard2_NG_D"             ,
					"TMT_Leopard2_NG_W"             ,
					"TMT_LEO2A4_w"                  ,
					"TMT_LEO2A4_E"                  ,
					"TMT_M60A3_E"                   ,
					"TMT_M60A3_W"                   ,
					"rhsusf_m109d_usarmy"           ,
					"rhsusf_M142_usarmy_D"          ,
					"UK3CB_B_M270_MLRS_Cluster_DES" ,
					"HAMF_GD240_Patrol2"         ,
					"HAMF_GD240_Unarmed2"        ,
					"HAMF_HMMWV1_Kornet"         ,
					"HAMF_HMMWV1_TOW"            ,
					"HAMF_VBL2_M50"              ,
					"HAMF_VBL2"                  ,
					"TMT_Cobra_RCWS_E"           ,
					"TMT_Cobra_RCWS_W"           ,
					"TMT_Kirpill_MRAP_E"         ,
					"TMT_Kirpill_MRAP_W"         ,
					"TMT_Ejder_RCWS_GEN"         ,
					"tmt_landrover"              ,
					"tmt_landrover_w"            ,
					"rhsusf_m1025_w_s_m2"        ,
					"rhsusf_m1025_w_s_Mk19"      ,
					"rhsusf_m1025_w_s"           ,
					"rhsusf_m1043_w_s_m2"        ,
					"rhsusf_m1043_w_s_mk19"      ,
					"rhsusf_m1043_w_s"           ,
					"rhsusf_m1045_w_s"           ,
					"rhsusf_m998_w_s_4dr_halftop",
					"rhsusf_m998_w_s_2dr_fulltop",
					"UK3CB_B_M270_MLRS_HE_DES"      ];
	nof_vehicles = 23;