	// Names of the Vehicles must match the Official names of the game
vehicle_names = [
	"walker_A3_boat_f"             ,  
"walker_A3_smallb_f"               ,
"walker_A3_smallb_e"               ,
"UK3CB_ADC_C_Fishing_Boat"         ,
"UK3CB_ADC_C_Fishing_Vessel"       ,
"UK3CB_ADC_C_Small_Boat_wood"      ,
"sab_nl_vessel_a"                  ,
"sab_nl_vessel_b"                  ,
"sab_nl_vessel_c"                  ,
"sab_nl_vessel_d"                  ,
"sab_nl_mutsuki"                   , 
"sab_nl_akagi"                     ,
"sab_nl_drone_a6m"                 ,
"sab_nl_scharnhorst"               ,
"sab_nl_t22"                       ,
"sab_nl_vincenzo"                  ,
"sab_nl_zara"                      ,
"rhsgref_hidf_rhib"                ,
"HAFM_Replenishment"               ,
"B_Lifeboat"                       ,
"HAFM_FREMM"                       ,
"B_Boat_Atmed_01_minigun_F"        ,
"HAFM_CB90_BLU"                    ,
"HAFM_MEKO_HN"                     ,
"HAFM_Russen"                      ,
"rhsusf_mkvsoc"                    ,
"SBOMB_CAR7"                       ,
"HAFM_Naval_CB90_BLU"              ,
"Lexx_ContainerShip_Black_Empty_H" ,
"Lexx_ContainerShip_Blue_Loaded_H" ,
"Lexx_ContainerShip_Green_Loaded_H",
"Lexx_CruiseShip_Blue_H"           ,
"HAFM_Naval_GunBoat_BLU"   ];
nof_vehicles = 17;